Repository OasisLMF/OasisUI, pull requests merged in 2019-02, with the labels that each got.

#27 fix/22-zip domnload
  BFE_RShiny/flamingo/R/ViewFilesInTable_module.R
Labels: bug

#29 feature/20-refresh-icon
  BFE_RShiny/flamingo/NAMESPACE
  BFE_RShiny/flamingo/R/landingpage_module.R
  BFE_RShiny/flamingo/R/shiny.R
  BFE_RShiny/flamingo/R/step1_choosePortfolio_module.R
  BFE_RShiny/flamingo/R/step2_chooseAnalysis_module.R
  BFE_RShiny/flamingo/R/step3_configureOutput_module.R
  BFE_RShiny/flamingo/inst/app/www/css/flamingo-tweaks.css
  BFE_RShiny/flamingo/man/flamingoRefreshButton.Rd
Labels: improvement

#30 feature/21-info-status
  BFE_RShiny/flamingo/R/API_analyses.R
  BFE_RShiny/flamingo/R/config_settings.R
Labels: enhancement

#31 fix for status_detailed ordering
  BFE_RShiny/flamingo/R/API_analyses.R
Labels: bug
